name: Deploy BuscaFri

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_TOKEN_VALUE: ${{ secrets.R2_TOKEN_VALUE }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python & Dependencies
        run: uv sync --dev

      - name: Run Linter
        run: uv run ruff check .

      - name: Run Common Tests
        run: uv run pytest tests/ -m "not integration"

      - name: Run Integration Tests
        run: uv run pytest tests/ -m integration -rs

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: victor_seabra_ba
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/buscafri
            export PATH="$HOME/.local/bin:$PATH"

            git pull origin main

            # Cria a pasta do rclone e gera o rclone.conf automaticamente usando o Secret do GitHub
            mkdir -p ~/.config/rclone/
            echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

            uv sync

            sudo systemctl restart buscafri-api
            sudo systemctl restart buscafri-streamlit
